name: CMake (Fedora Linux)

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo
  BUILD_NUMBER: ${{github.run_number}}
  QT_QPA_PLATFORM: offscreen
  CMAKE_BUILD_PARALLEL_LEVEL: 3

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['fedora:38', 'fedora:39']
        include:
        - container: 'fedora:38'
          name: fedora38
        - container: 'fedora:39'
          name: fedora39

    steps:
      - name: Install Deps
        run: dnf install -y git gcc-c++ cmake rpm-build openssl-devel pcsc-lite-devel qt6-qtsvg-devel qt6-qttools-devel gtest-devel

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr -B build -S .

      - name: Build
        run: cmake --build build --config $BUILD_TYPE --target package

      - uses: actions/upload-artifact@v4
        with:
          name: web-eid-app-fedora-build-${{matrix.name}}-${{github.run_number}}
          path: build/*rpm
